/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import controler.Controler;
import domen.IDomain;
import domen.NacinIzrade;
import domen.KucicaZaPse;
import domen.TipKuciceZaPse;
import java.awt.Dialog;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import model.TableModelNaciniIzrade;
import session.Session;

/**
 *
 * @author Win 7
 */
public class FrmKucicaZaPse extends javax.swing.JDialog {

    KucicaZaPse kucicaRef;
    FrmPretragaKuciceZaPse frmPretraga;
    GlavnaForma frmGlavna;

    /**
     * Creates new form FrmKucicaZaPse
     */
    public FrmKucicaZaPse(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        popuniCmbTipovi();
        setLocationRelativeTo(null);
        prepareForm(FormMode.NEW);
        jButton1.setVisible(false);

    }

    FrmKucicaZaPse(java.awt.Frame parent, boolean modal, int idKucicaZaPse, FrmPretragaKuciceZaPse frmPretraga, GlavnaForma frmGlavna) {
        super(parent, modal);
        initComponents();
        this.frmGlavna = frmGlavna;
        this.frmPretraga = frmPretraga;
        popuniCmbTipovi();
        setLocationRelativeTo(null);
        pripremiFomuZaPromene(idKucicaZaPse);
       // vratiSveNacinaZaKucicuZaPse(idKucicaZaPse);ovo dodaj!

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbTipovi = new javax.swing.JComboBox();
        btnSacuvaj = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        btnPokreniIzmenu = new javax.swing.JButton();
        btnOtkazi = new javax.swing.JButton();
        btnPretaga = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNacini = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Naziv kucice za pse:");

        txtNaziv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNazivActionPerformed(evt);
            }
        });

        jLabel2.setText("Tip kucice za pse:");

        cmbTipovi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTipovi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoviActionPerformed(evt);
            }
        });

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnPokreniIzmenu.setText("Pokreni izmenu");
        btnPokreniIzmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPokreniIzmenuActionPerformed(evt);
            }
        });

        btnOtkazi.setText("Otkazi");
        btnOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtkaziActionPerformed(evt);
            }
        });

        btnPretaga.setText("Pretrazi");
        btnPretaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretagaActionPerformed(evt);
            }
        });

        tblNacini.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblNacini);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbTipovi, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(57, 57, 57)
                            .addComponent(btnPretaga, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnOtkazi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnPokreniIzmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbTipovi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnPretaga)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIzmeni)
                    .addComponent(btnPokreniIzmenu)
                    .addComponent(btnSacuvaj)
                    .addComponent(btnOtkazi))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton1.setText("Prikazi izradu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed

        try {
            String naziv = txtNaziv.getText().trim();
            TipKuciceZaPse tip = (TipKuciceZaPse) cmbTipovi.getSelectedItem();
            KucicaZaPse kzp = new KucicaZaPse(naziv, tip);
            if (naziv.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Morate uneti sva polja!");
            }
            System.out.println("ovo je kucica za pse " + kzp.getNazivKuciceZaPse());
            kucicaRef = Controler.getInstance().zapamtiKucicuZaPse(kzp);
            JOptionPane.showMessageDialog(this, "Sistem je zapamtio kucicu za pse!");

            int result = JOptionPane.showConfirmDialog(null, "Da li zelite uneti jos neku kucicu za pse?");
            if (result == JOptionPane.YES_OPTION) {
                this.dispose();
                JDialog frm = new FrmKucicaZaPse(null, true);
                frm.setVisible(true);
            } else {
                dispose();
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Sistem ne moze da zapamti kucicu za pse!");
            Logger.getLogger(FrmKucicaZaPse.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Sistem ne moze da zapamti kucicu za pse!");
            Logger.getLogger(FrmKucicaZaPse.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed

        String naziv = txtNaziv.getText().trim();
        TipKuciceZaPse tip = (TipKuciceZaPse) cmbTipovi.getSelectedItem();
        KucicaZaPse kzp = new KucicaZaPse(kucicaRef.getKucicaZaPseId(), naziv, tip);

        if (naziv.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Morate uneti sva polja!!!");
            return;
        }
        try {
            kzp = Controler.getInstance().izmeniKucicuZaPse(kzp);
            JOptionPane.showMessageDialog(null, "Sistem je azurirao kucicu za pse!");
            JOptionPane.showMessageDialog(null, "Sistem ne moze da izmeni kucicu za pse!");
            dispose();
            frmPretraga.popuniTabeluKucicaZaPse();
            frmPretraga.pripremiZaPretragu();
        } catch (ClassNotFoundException ex) {
            //Logger.getLogger(FrmKucicaZaPse.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Sistem ne moze da izmeni kucicu za pse!");
        } catch (Exception ex) {
            //Logger.getLogger(FrmKucicaZaPse.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Sistem ne moze da izmeni kucicu za pse!");
        }


    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnPokreniIzmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPokreniIzmenuActionPerformed

        frmGlavna.postaviStatus("Use case: Azuriranje podataka o proizvodima!");
        prepareForm(FormMode.EDIT);
    }//GEN-LAST:event_btnPokreniIzmenuActionPerformed

    private void btnPretagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretagaActionPerformed
        FrmPretragaTipaKuciceZaPse frmPretraga = new FrmPretragaTipaKuciceZaPse(frmGlavna, true);
        frmPretraga.setVisible(true);
    }//GEN-LAST:event_btnPretagaActionPerformed

    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziActionPerformed
        dispose();
    }//GEN-LAST:event_btnOtkaziActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if (Session.getInstance().getMap().containsKey("izabraniTipKuciceZaPse")) {
            TipKuciceZaPse tip = (TipKuciceZaPse) Session.getInstance().getMap().get("izabraniTipKuciceZaPse");
            cmbTipovi.setSelectedItem(tip);
        }

    }//GEN-LAST:event_formWindowActivated

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if (Session.getInstance().getMap().containsKey("izabraniTipKuciceZaPse")) {
            Session.getInstance().getMap().remove("izabraniTipKuciceZaPse");

        }
    }//GEN-LAST:event_formWindowClosed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int selektovani = tblNacini.getSelectedRow();
        if (selektovani >= 0) {
            int id = (int) tblNacini.getValueAt(selektovani, 0);

            JOptionPane.showMessageDialog(null, "Sistem je nasao podatke o izabranom nacinu izrade. Izabrani nacn izrade ima ID: " + id);

            JDialog frmNacinIzrade = new FrmNacinIzrade(null, true, id, this, frmGlavna);
            frmNacinIzrade.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Sistem ne moze da pronadje nacin izrade.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNazivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNazivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNazivActionPerformed

    private void cmbTipoviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoviActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoviActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JButton btnPokreniIzmenu;
    private javax.swing.JButton btnPretaga;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox cmbTipovi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNacini;
    private javax.swing.JTextField txtNaziv;
    // End of variables declaration//GEN-END:variables

    private void popuniCmbTipovi() {
        try {
            cmbTipovi.removeAllItems();
            List<TipKuciceZaPse> lista = Controler.getInstance().vratiListuTipova();
            for (IDomain tip : lista) {
                if (tip instanceof TipKuciceZaPse) {
                    cmbTipovi.addItem((TipKuciceZaPse) tip);
                }
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Sistem ne moze da ucita listu tipova kucica za pse");
            Logger.getLogger(FrmKucicaZaPse.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Sistem ne moze da ucita listu tipova kucica za pse");
            Logger.getLogger(FrmKucicaZaPse.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void prepareForm(FormMode mode) {
        switch (mode) {
            case EDIT:
                btnIzmeni.setEnabled(true);

                btnPokreniIzmenu.setEnabled(false);
                btnSacuvaj.setEnabled(false);
                btnIzmeni.setEnabled(true);
                btnPretaga.setEnabled(true);

                txtNaziv.setVisible(true);

                cmbTipovi.setEnabled(true);
                txtNaziv.setEnabled(true);

                break;
            case NEW:
                btnIzmeni.setEnabled(false);

                btnPokreniIzmenu.setEnabled(false);
                btnSacuvaj.setEnabled(true);
                btnOtkazi.setEnabled(true);
                btnPretaga.setEnabled(true);

                txtNaziv.setVisible(true);
                txtNaziv.setEnabled(true);
                cmbTipovi.setEnabled(true);
                break;
            case VIEW:
                btnIzmeni.setEnabled(false);

                btnPokreniIzmenu.setEnabled(true);
                btnSacuvaj.setEnabled(false);
                btnOtkazi.setEnabled(false);
                btnPretaga.setEnabled(false);

                txtNaziv.setVisible(true);
                txtNaziv.setEnabled(false);

                cmbTipovi.setEnabled(false);
                break;
        }
    }

    private void pripremiFomuZaPromene(int idKucicaZaPse) {
        prepareForm(FormMode.VIEW);

        try {
            kucicaRef = Controler.getInstance().vratiKucicuZaPsePoId(idKucicaZaPse);
            setTitle("Pregled kucice za pse " + kucicaRef.getNazivKuciceZaPse());
            txtNaziv.setText(kucicaRef.getNazivKuciceZaPse());
            cmbTipovi.setSelectedItem(kucicaRef.getTipKuciceZaPse());
            List<NacinIzrade> nacini = Controler.getInstance().vratiNacineZaKuciceZaPse(kucicaRef);
            TableModelNaciniIzrade model = new TableModelNaciniIzrade(nacini);
            tblNacini.setModel(model);
            jButton1.setVisible(true);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Sistem ne moze da nadje proizvod po zadatkom id!!");
            Logger.getLogger(FrmKucicaZaPse.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Sistem ne moze da nadje proizvod po zadatkom id!!");
            Logger.getLogger(FrmKucicaZaPse.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
}
